import { Hub, ProcessStep, Industry, IndustryProfile } from '@/types';

export const HUBS: Record<string, Hub> = {
  ncr: {
    id: 'ncr',
    name: 'NCR Hub',
    region: 'Luzon',
    city: 'Metro Manila / Quezon City',
    address: 'TBA - Metro Manila/Quezon City',
    phone: '+63-2-XXXX-XXXX',
    email: 'ncr@fssoftwares.ph',
    timezone: 'PHT (UTC+8)',
    manager: 'Hub Manager (NCR)',
    coverage: ['Luzon', 'Northern Philippines', 'Metro Manila', 'Cavite', 'Laguna'],
  },
  cebu: {
    id: 'cebu',
    name: 'Cebu Hub',
    region: 'Visayas',
    city: 'Cebu City',
    address: 'TBA - Cebu City',
    phone: '+63-32-XXX-XXXX',
    email: 'cebu@fssoftwares.ph',
    timezone: 'PHT (UTC+8)',
    manager: 'Hub Manager (Cebu)',
    coverage: ['Visayas', 'Central Philippines', 'Cebu', 'Bohol', 'Negros'],
  },
  davao: {
    id: 'davao',
    name: 'Davao Headquarters',
    region: 'Mindanao',
    city: 'Davao City',
    address: 'TBA - Davao City',
    phone: '+63-82-XXX-XXXX',
    email: 'davao@fssoftwares.ph',
    timezone: 'PHT (UTC+8)',
    manager: 'Fritz Suarez (Founder)',
    coverage: ['Mindanao', 'Southern Philippines', 'Davao', 'GenSan', 'Zamboanga'],
  },
};

export const PROCESS_STEPS: ProcessStep[] = [
  {
    number: 1,
    title: 'Introduction & Discovery',
    description: 'Initial consultation and needs assessment',
    phase: 'discovery',
    icon: 'handshake',
    details: ['Understand your business goals', 'Assess current processes', 'Identify key pain points'],
    outcomes: ['Discovery document', 'Initial roadmap'],
  },
  {
    number: 2,
    title: 'Portfolio Learning Walkthrough',
    description: 'Explore relevant solutions for your business',
    phase: 'discovery',
    icon: 'book',
    details: ['Product demonstrations', 'Use case exploration', 'Feature walkthrough'],
    outcomes: ['Product recommendations', 'Feature alignment map'],
  },
  {
    number: 3,
    title: 'Business Requirement Identification',
    description: 'Document workflows and operational needs',
    phase: 'discovery',
    icon: 'clipboard',
    details: ['Workflow documentation', 'Integration requirements', 'User role definition'],
    outcomes: ['Requirements document', 'Process flows'],
  },
  {
    number: 4,
    title: 'Executive Collaboration',
    description: 'Stakeholder alignment and decision-making',
    phase: 'design',
    icon: 'users',
    details: ['Stakeholder meetings', 'Budget alignment', 'Executive sign-off'],
    outcomes: ['Stakeholder approval', 'Budget allocation'],
  },
  {
    number: 5,
    title: 'Solution Mapping & Pattern Selection',
    description: 'Choose Pattern A or B architecture for your needs',
    phase: 'design',
    icon: 'layout',
    details: ['Architecture selection', 'Technology stack review', 'Deployment profile choice'],
    outcomes: ['Architecture document', 'Technical roadmap'],
  },
  {
    number: 6,
    title: 'Proposal & Commercial Terms',
    description: 'Scope definition, timeline, and investment breakdown',
    phase: 'design',
    icon: 'file-text',
    details: ['Detailed proposal', 'Timeline planning', 'Commercial terms'],
    outcomes: ['Signed proposal', 'Project charter'],
  },
  {
    number: 7,
    title: 'Pre-Transfer Knowledge Transfer ⭐',
    description: 'The hinge between delivery and operational ownership',
    phase: 'delivery',
    icon: 'lightbulb',
    details: ['Train operational users', 'Build system understanding', 'Prepare for handover'],
    outcomes: ['Trained team', 'Knowledge transfer docs'],
  },
  {
    number: 8,
    title: 'Build, Deployment & Go-Live',
    description: 'Pattern B build, E2E testing, and phased rollout',
    phase: 'delivery',
    icon: 'rocket',
    details: ['Development completion', 'Comprehensive testing', 'Regional deployment coordination'],
    outcomes: ['Live system', 'Deployment report'],
  },
  {
    number: 9,
    title: 'Post-Go-Live Support',
    description: 'Managed support, continuous improvement, quarterly reviews',
    phase: 'delivery',
    icon: 'life-buoy',
    details: ['Ongoing technical support', 'Performance monitoring', 'Continuous optimization'],
    outcomes: ['Support tickets resolved', 'Quarterly insights'],
  },
];

export const INDUSTRIES: IndustryProfile[] = [
  {
    id: 'telecommunications',
    name: 'Telecommunications & Infrastructure',
    description: 'Cell towers, infrastructure projects, nationwide rollouts',
    painPoints: [
      'Multi-site tower asset tracking',
      'Maintenance scheduling complexity',
      'Real-time deployment visibility',
    ],
    solutions: ['SiteAcquire', 'TowerAsset', 'FieldOps', 'SCADA'],
    regionalExamples: [
      { hub: 'ncr', example: 'Cell tower rollout in NCR region' },
      { hub: 'cebu', example: 'Infrastructure projects in Visayas' },
      { hub: 'davao', example: 'Nationwide tower network management' },
    ],
    icon: 'radio-tower',
    color: '#10B981',
  },
  {
    id: 'construction',
    name: 'Construction & Real Estate',
    description: 'Multi-site oversight, 3D modeling, cost estimation',
    painPoints: [
      'Multiple project coordination',
      'Material cost tracking',
      'Stakeholder communication',
    ],
    solutions: ['ConstructPM', 'BIM Suite', 'QuantitySurvey', 'PropertyPMS'],
    regionalExamples: [
      { hub: 'ncr', example: 'High-rise developments in Metro Manila' },
      { hub: 'cebu', example: 'Commercial construction in Cebu' },
      { hub: 'davao', example: 'Regional development projects' },
    ],
    icon: 'hard-hat',
    color: '#10B981',
  },
  {
    id: 'healthcare',
    name: 'Healthcare & Medical',
    description: 'Clinics, hospitals, patient records, labs',
    painPoints: [
      'Patient data management',
      'Appointment scheduling',
      'Lab result tracking',
    ],
    solutions: ['EHR', 'PracticeSuite', 'LIMS', 'InstitutionCare', 'CareOps'],
    regionalExamples: [
      { hub: 'ncr', example: 'Hospital networks in Manila' },
      { hub: 'cebu', example: 'Clinic chains in Visayas' },
      { hub: 'davao', example: 'Healthcare facilities in Mindanao' },
    ],
    icon: 'heart',
    color: '#10B981',
  },
  {
    id: 'hospitality',
    name: 'Hospitality & Tourism',
    description: 'Hotels, resorts, restaurants, tour operators',
    painPoints: [
      'Booking and reservation management',
      'Guest experience coordination',
      'Multi-property operations',
    ],
    solutions: ['HotelPMS', 'Reserve', 'TravelOps', 'DineOps'],
    regionalExamples: [
      { hub: 'ncr', example: 'Hotel chains in Manila' },
      { hub: 'cebu', example: 'Boracay and island resorts' },
      { hub: 'davao', example: 'Davao tourism operations' },
    ],
    icon: 'bed',
    color: '#10B981',
  },
  {
    id: 'retail',
    name: 'Retail & Distribution',
    description: 'Multi-branch retail, inventory, POS systems',
    painPoints: [
      'Inventory synchronization',
      'Sales tracking across branches',
      'Supply chain management',
    ],
    solutions: ['POS', 'Inventory', 'CRM', 'Customer Growth Bundle'],
    regionalExamples: [
      { hub: 'ncr', example: 'Retail chains across Luzon' },
      { hub: 'cebu', example: 'Island retail operations' },
      { hub: 'davao', example: 'Nationwide retail expansion' },
    ],
    icon: 'shopping-bag',
    color: '#10B981',
  },
  {
    id: 'logistics',
    name: 'Logistics & Transportation',
    description: 'Fleet management, delivery operations, tracking',
    painPoints: [
      'Vehicle tracking and routing',
      'Driver management',
      'Real-time delivery updates',
    ],
    solutions: ['FleetHaul', 'FieldOps', 'SCADA'],
    regionalExamples: [
      { hub: 'ncr', example: '200+ vehicle fleet in NCR' },
      { hub: 'cebu', example: 'Visayas regional logistics' },
      { hub: 'davao', example: 'Nationwide logistics network' },
    ],
    icon: 'truck',
    color: '#10B981',
  },
  {
    id: 'professional-services',
    name: 'Professional Services',
    description: 'Law firms, agencies, consultants, IT departments',
    painPoints: [
      'Project and time tracking',
      'Client billing',
      'Resource allocation',
    ],
    solutions: ['PSA', 'LegalPM', 'ITSM', 'AgencyPro'],
    regionalExamples: [
      { hub: 'ncr', example: 'Law firms in Manila' },
      { hub: 'cebu', example: 'Recruitment agencies in Cebu' },
      { hub: 'davao', example: 'Consulting firms nationwide' },
    ],
    icon: 'briefcase',
    color: '#10B981',
  },
  {
    id: 'education',
    name: 'Education & Training',
    description: 'Schools, universities, training centers',
    painPoints: [
      'Student enrollment management',
      'Course scheduling',
      'Certification tracking',
    ],
    solutions: ['CampusOps', 'TrainCert'],
    regionalExamples: [
      { hub: 'ncr', example: 'University systems in Metro Manila' },
      { hub: 'cebu', example: 'Educational institutions in Visayas' },
      { hub: 'davao', example: 'Training centers nationwide' },
    ],
    icon: 'book-open',
    color: '#10B981',
  },
  {
    id: 'manufacturing',
    name: 'Manufacturing & Industrial',
    description: 'Factories, equipment monitoring, compliance',
    painPoints: [
      'Equipment maintenance scheduling',
      'Production tracking',
      'Safety compliance',
    ],
    solutions: ['APM', 'EHS', 'SCADA', 'Inventory'],
    regionalExamples: [
      { hub: 'ncr', example: 'Manufacturing in Laguna' },
      { hub: 'cebu', example: 'Industrial facilities in Visayas' },
      { hub: 'davao', example: 'Manufacturing operations nationwide' },
    ],
    icon: 'factory',
    color: '#10B981',
  },
  {
    id: 'security',
    name: 'Security & Facilities',
    description: 'Security agencies, guard scheduling, facilities management',
    painPoints: [
      'Guard shift scheduling',
      'Client account management',
      'Incident reporting',
    ],
    solutions: ['SecureOps', 'PropertyPMS', 'EHS'],
    regionalExamples: [
      { hub: 'ncr', example: 'Security agencies in Manila' },
      { hub: 'cebu', example: 'Regional security operations' },
      { hub: 'davao', example: 'Nationwide security network' },
    ],
    icon: 'shield',
    color: '#10B981',
  },
  {
    id: 'beauty-wellness',
    name: 'Beauty, Wellness & Fitness',
    description: 'Salons, gyms, wellness centers, spas',
    painPoints: [
      'Appointment and class scheduling',
      'Member management',
      'Service package tracking',
    ],
    solutions: ['GlowFit', 'Reserve', 'CareOps'],
    regionalExamples: [
      { hub: 'ncr', example: 'Gym chains across Metro Manila' },
      { hub: 'cebu', example: 'Wellness centers in Cebu' },
      { hub: 'davao', example: 'Beauty and fitness nationwide' },
    ],
    icon: 'heart-handshake',
    color: '#10B981',
  },
  {
    id: 'specialized',
    name: 'Specialized Services',
    description: 'Entertainment, funeral services, event production',
    painPoints: [
      'Event and talent management',
      'Booking coordination',
      'Client relationship management',
    ],
    solutions: ['ShowBiz', 'MemorialCare', 'DineOps'],
    regionalExamples: [
      { hub: 'ncr', example: 'Entertainment production in Manila' },
      { hub: 'cebu', example: 'Event services in Visayas' },
      { hub: 'davao', example: 'Specialized services nationwide' },
    ],
    icon: 'star',
    color: '#10B981',
  },
];

export const PRODUCT_CATEGORIES = [
  {
    id: 'infrastructure',
    name: 'Infrastructure & Construction',
    icon: 'construction',
    description: '5 solutions for building, telecom, and infrastructure projects',
    color: '#10B981',
  },
  {
    id: 'property',
    name: 'Property & Hospitality',
    icon: 'building',
    description: '3 solutions for property and hospitality management',
    color: '#059669',
  },
  {
    id: 'healthcare',
    name: 'Healthcare & Wellness',
    icon: 'heart',
    description: '6 solutions for medical and wellness operations',
    color: '#10B981',
  },
  {
    id: 'logistics',
    name: 'Logistics & Field Ops',
    icon: 'truck',
    description: '4 solutions for logistics and field management',
    color: '#A7F3D0',
  },
  {
    id: 'operations',
    name: 'Business Operations',
    icon: 'briefcase',
    description: '8 solutions for core business operations',
    color: '#059669',
  },
  {
    id: 'specialized',
    name: 'Specialized Services',
    icon: 'sparkles',
    description: '8 solutions for niche industry needs',
    color: '#10B981',
  },
];

export const COLORS = {
  primary: {
    green: '#10B981',
    darkGreen: '#059669',
    lightGreen: '#A7F3D0',
  },
  secondary: {
    navy: '#1E293B',
    darkNavy: '#0F172A',
  },
  accent: {
    silver: '#E2E8F0',
    darkSilver: '#CBD5E1',
    lightGreen: '#D1FAE5',
  },
  backgrounds: {
    dark: '#0F1117',
    card: '#1A202C',
  },
  text: {
    primary: '#F1F5F9',
    secondary: '#94A3B8',
  },
};

export const FEATURE_HIGHLIGHTS = [
  {
    title: 'Pattern B Architecture',
    description: 'Tauri + Flutter + API | Cloud-native, cross-platform, scalable',
    icon: 'zap',
  },
  {
    title: 'E2E Tested',
    description: 'Production-ready across 4 deployment profiles',
    icon: 'check-circle',
  },
  {
    title: 'Pre-Transfer Knowledge',
    description: 'Your team owns the system, not just IT',
    icon: 'lightbulb',
  },
  {
    title: 'Nationwide Coverage',
    description: '3 hubs: NCR, Cebu, Davao with local presence',
    icon: 'map-pin',
  },
];
